### ISSUE TITLE
Install Vendors

### ISSUE THREAD

**Issue by maxwellqc13** [blitze/phpBB-ext-sitemaker#32]
I do not understand what this part of the install is.   I uploaded all the files to ext folder and seems to work correct so what am I missing?

`Install vendors

php composer.phar install --dev
`

**Comment by blitze** [comment]
Since we are on Github, the installation instructions here are for someone who is cloning the repo with intentions to help with the development of the extension. If you downloaded the extension from http://phpbb-sitemaker.website/ it already has the vendors and everything you need. You just need to put it in the phpBB/ext/ folder and install from ACP.
