### ISSUE TITLE
Lost folder styles/all/theme

### ISSUE THREAD

**Issue by demonlibra** [blitze/phpBB-ext-sitemaker#64]
Good day.
Versions 3.3.0 and 3.3.1 does not contain folder styles/all/theme

**Comment by blitze** [comment]
hi dmonlibra,

this was actually an intentional change. It is not good practice to store binary files on Github. So if you are cloning the repo, you will need to run `yarn install` followed by `yarn build` or `yarn start`. But you can go to [releases ](https://github.com/blitze/phpBB-ext-sitemaker/releases) to get the zip file that includes the assets (binary files).

thanks

**Comment by demonlibra** [comment]
Thnak you.
